name: projet-jaugey-suillot
channels:
  - defaults
dependencies:
  - python=3.7.9
  - pip:
    - tensorflow==2.2.2
    - matplotlib==3.3.3
    - numpy==1.18.5
    - opencv-python==4.5.1.48
    - pyinstaller==4.2